### ISSUE TITLE
Integration in another project

### ISSUE THREAD

**Issue by mathrb** [NoRedInk/tracing-newrelic#4]
Hello,

First of all: I'm new to haskell.

I'm trying to integrate this project into another one: [duckling](https://github.com/facebook/duckling).
In duckling project, there's a .cabal file and a stack file.
I integrated the reference to your library in the duckling.cabal as a build-depends : tracing-newrelic of an executable (duckling-example-exe)
I updated the stack.yml to add this github project as extra-deps.
I also updated the resolver to lts-13-11 (ghc-8.6.3) so that building does not fail on the Setup.hs in your repository.

The last issue I'm having is the linking phase:
```
Linking .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/duckling-example-exe/duckling-example-exe ...
/usr/bin/ld.gold: error: cannot find -lnewrelic
/home/mathias/.stack/snapshots/x86_64-linux-tinfo6/f513ca64ed958f201693109c1443c29700f162f3aed5ec4f93a29537397e2f58/8.6.3/lib/x86_64-linux-ghc-8.6.3/tracing-newrelic-1.0.0.0-66jYv20dOhbLS0uc6R9JxW/libHStracing-newrelic-1.0.0.0-66jYv20dOhbLS0uc6R9JxW.a(NewRelic.o)(.text+0x127b8): error: undefined reference to 'newrelic_init'
```
There are a lot more undefined references, but I don't think I need to paste all of them.
I cloned the c-sdk and built it. I didn't run the daemon, I don't think we need it running to build the project, right?

So my questions in the end are:
- Is it because I'm using stack ?
- Do you have any idea why is this would not work?

Kind regards

PS: to reproduce
`git clone https://github.com/facebook/duckling.git`
update stack.yml:
```yaml
resolver: lts-13.11

packages:
- '.'

extra-deps: 
  - github: NoRedInk/tracing-newrelic
    commit: ee26c605455cedf59e36de22fb6acc3696d23745
  

flags: {}

extra-package-dbs: []
```
in duckling.cabal:
Line 1166:                     , tracing-newrelic
